services:
  chromium:
    image: chromedp/headless-shell:latest
    restart: unless-stopped
    command:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--remote-debugging-address=0.0.0.0"
      - "--remote-debugging-port=9223"
